# Generated by Django 5.2.3 on 2025-06-30 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/files/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('pptx', 'PowerPoint'), ('image', 'Image'), ('audio', 'Audio'), ('other', 'Other')], max_length=10)),
                ('purpose', models.CharField(choices=[('summary', 'Summary'), ('audio', 'Text-to-Speech'), ('qa', 'Question Generation'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='uploads/audio/')),
                ('source_type', models.CharField(choices=[('tts', 'Text-to-Speech'), ('transcription', 'Transcription')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_audio', to='files.file')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('file', 'File'), ('transcript', 'Transcript'), ('chat', 'Chat')], max_length=20)),
                ('source_id', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField()),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='files.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
