# Generated by Django 5.2.3 on 2025-07-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestion',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='visual_aid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
