# Generated by Django 5.2.3 on 2025-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_generatedquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='text_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
