# Generated by Django 5.2.3 on 2025-07-12 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_audio_text_input'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='uploads/summaries/')),
                ('format', models.CharField(choices=[('text', 'Text'), ('file', 'File')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_audio_generated', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='files.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
