# Generated by Django 5.2.3 on 2025-07-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_filesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='audio',
            name='voice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
