# Generated by Django 5.2.3 on 2025-06-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcollaborator',
            old_name='can_edit',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='chatcollaborator',
            name='access_level',
            field=models.CharField(choices=[('view', 'View Only'), ('edit', 'Can Edit')], default='view', max_length=10),
        ),
    ]
