# Generated by Django 5.2.3 on 2025-06-30 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestChatTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
