# Generated by Django 5.2.3 on 2025-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_auth', '0002_guestchattracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestIPTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
